name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: wasm-pack build --target web --scope i-vresse
    - name: Build post-process
      run: |
        perl -pi -e 's/\"module\"/"type": "module", "main"/' pkg/package.json
    - name: Run rust tests
      run: wasm-pack test --node
    - name: Run node tests
      run: node --test tests